export const appConstants = {
    /* Create app */
    CREATE_APP_START: 'CREATE_APP_START',
    CREATE_APP_SUCCESS: 'CREATE_APP_SUCCESS',
    CREATE_APP_FAILURE: 'CREATE_APP_FAILURE',

    /* Fetch all */
    FETCH_APPS_START: 'FETCH_APPS_START',
    FETCH_APPS_SUCCESS: 'FETCH_APPS_SUCCESS',
    FETCH_APPS_FAILURE: 'FETCH_APPS_FAILURE',

    /* Fetch one */
    FETCH_APP_START: 'FETCH_APP_START',
    FETCH_APP_SUCCESS: 'FETCH_APP_SUCCESS',
    FETCH_APP_FAILURE: 'FETCH_APP_FAILURE',

    /* Fetch build settings*/
    FETCH_BUILD_OPTIONS_START: 'FETCH_BUILD_OPTIONS_START',
    FETCH_BUILD_OPTIONS_SUCCESS: 'FETCH_BUILD_OPTIONS_SUCCESS',
    FETCH_BUILD_OPTIONS_FAILURE: 'FETCH_BUILD_OPTIONS_FAILURE',

    /* Fetch builds */
    FETCH_BUILDS_START: 'FETCH_BUILDS_START',
    FETCH_BUILDS_SUCCESS: 'FETCH_BUILDS_SUCCESS',
    FETCH_BUILDS_FAILURE: 'FETCH_BUILDS_FAILURE',

     /* Fetch build */
     FETCH_BUILD_START: 'FETCH_BUILD_START',
     FETCH_BUILD_SUCCESS: 'FETCH_BUILD_SUCCESS',
     FETCH_BUILD_FAILURE: 'FETCH_BUILD_FAILURE',

    /* Deploy */
    DEPLOY_START: 'DEPLOY_START',
    DEPLOY_SUCCESS: 'DEPLOY_SUCCESS',
    DEPLOY_FAILURE: 'DEPLOY_FAILURE',

    /* Fetch stats */
    FETCH_STATS_START: 'FETCH_STATS_START',
    FETCH_STATS_SUCCESS: 'FETCH_STATS_SUCCESS',
    FETCH_STATS_FAILURE: 'FETCH_STATS_FAILURE'

}
