export const appConstants = {

    /* CREATE APP */
    CREATE_APP_START: 'CREATE_APP_START',
    CREATE_APP_SUCCESS: 'CREATE_APP_SUCCESS',
    CREATE_APP_FAILURE: 'CREATE_APP_FAILURE',

    /* FETCH ALL APPS */
    FETCH_APPS_START: 'FETCH_APPS_START',
    FETCH_APPS_SUCCESS: 'FETCH_APPS_SUCCESS',
    FETCH_APPS_FAILURE: 'FETCH_APPS_FAILURE',

    /* FETCH APP */
    FETCH_APP_START: 'FETCH_APP_START',
    FETCH_APP_SUCCESS: 'FETCH_APP_SUCCESS',
    FETCH_APP_FAILURE: 'FETCH_APP_FAILURE',

    /* FETCH BUILD OPTIONS */
    FETCH_BUILD_OPTIONS_START: 'FETCH_BUILD_OPTIONS_START',
    FETCH_BUILD_OPTIONS_SUCCESS: 'FETCH_BUILD_OPTIONS_SUCCESS',
    FETCH_BUILD_OPTIONS_FAILURE: 'FETCH_BUILD_OPTIONS_FAILURE',

    /* FETCH BUILDS */
    FETCH_BUILDS_START: 'FETCH_BUILDS_START',
    FETCH_BUILDS_SUCCESS: 'FETCH_BUILDS_SUCCESS',
    FETCH_BUILDS_FAILURE: 'FETCH_BUILDS_FAILURE',

    /* FETCH BUILD */
    FETCH_BUILD_START: 'FETCH_BUILD_START',
    FETCH_BUILD_SUCCESS: 'FETCH_BUILD_SUCCESS',
    FETCH_BUILD_FAILURE: 'FETCH_BUILD_FAILURE',

    /* DEPLOY */
    DEPLOY_START: 'DEPLOY_START',
    DEPLOY_SUCCESS: 'DEPLOY_SUCCESS',
    DEPLOY_FAILURE: 'DEPLOY_FAILURE',

    /* FETCH STATS */
    FETCH_STATS_START: 'FETCH_STATS_START',
    FETCH_STATS_SUCCESS: 'FETCH_STATS_SUCCESS',
    FETCH_STATS_FAILURE: 'FETCH_STATS_FAILURE',

    /* FETCH LOGS */
    FETCH_LOGS_START: 'FETCH_LOGS_START',
    FETCH_LOGS_SUCCESS: 'FETCH_LOGS_SUCCESS',
    FETCH_LOGS_FAILURE: 'FETCH_LOGS_FAILURE',

    /* FETCH CONTAINER OPTIONS */
    FETCH_CONTAINER_OPTIONS_START: 'FETCH_CONTAINER_OPTIONS_START',
    FETCH_CONTAINER_OPTIONS_SUCCESS: 'FETCH_CONTAINER_OPTIONS_SUCCESS',
    FETCH_CONTAINER_OPTIONS_FAILURE: 'FETCH_CONTAINER_OPTIONS_FAILURE',

    SET_CONTAINER_RAM: 'SET_CONTAINER_RAM'
}
