export const appConstants = {
    /* Create app */
    CREATE_APP_START: 'CREATE_APP_START',
    CREATE_APP_SUCCESS: 'CREATE_APP_SUCCESS',
    CREATE_APP_FAILURE: 'CREATE_APP_FAILURE',

    /* Fetch */
    FETCH_APPS_START: 'FETCH_APPS_START',
    FETCH_APPS_SUCCESS: 'FETCH_APPS_SUCCESS',
    FETCH_APPS_FAILURE: 'FETCH_APPS_FAILURE',
}
