export const userConstants = {
    REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
    REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
    REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',

    AUTHENTICATE_REQUEST: 'USERS_AUTHENTICATE_REQUEST',
    AUTHENTICATE_SUCCESS: 'USERS_AUTHENTICATE_SUCCESS',
    AUTHENTICATE_FAILURE: 'USERS_AUTHENTICATE_FAILURE',

    LOGOUT: 'USERS_LOGOUT'
}